### ISSUE TITLE
tom-select Input Height

### ISSUE THREAD

**Issue by reasecret** [mostafizurhimself/admintoolkit-html#178]
I've a select input like this:
![resim](https://github.com/mostafizurhimself/admintoolkit-html/assets/32717963/2d22becb-8c60-4d2e-a782-78d7facaccfd)
Maybe you can see, there are 5 tags and last one is not showing. How can I use this input for auto height?

**Comment by mostafizurhimself** [comment]
@reasecret A quick solution will be, just add this class in your css file.

```css
.tom-select>.ts-control {
    min-width: 2.5rem; 
    height: auto;
 }
 ```
